# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/18 16:25:03 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Fixed_point

CLASS = Class

SOURCES = main.cpp \
	  $(CLASS)/Fixed.cpp

include ../../MakefileTemplate
