# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/18 21:43:01 by romain           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = DiamondTrap

CLASS = Class

SOURCES = main.cpp \
	  $(CLASS)/ClapTrap.cpp $(CLASS)/ScavTrap.cpp \
	  $(CLASS)/FragTrap.cpp $(CLASS)/DiamondTrap.cpp

include ../../MakefileTemplate

FLAGS +=  -Wshadow -Wno-shadow
