# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/31 19:04:38 by romain           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Bureaucrat

CLASS = Class

SOURCES = main.cpp \
	  $(addprefix $(CLASS)/,	\
	  Bureaucrat.cpp Form.cpp \
	  ShrubberyCreationForm.cpp \
	  RobotomyRequestForm.cpp \
	  PresidentialPardonForm.cpp)

include ../../MakefileTemplate
