# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/27 17:00:30 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = DiamondTrap

CLASS = Class

SOURCES = main.cpp \
	  $(CLASS)/Bureaucrat.cpp

include ../../MakefileTemplate

FLAGS +=  -Wshadow -Wno-shadow
