# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/24 21:32:21 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = DiamondTrap

CLASS = Class


SOURCES = main.cpp \
	  $(CLASS)/ClapTrap.cpp $(CLASS)/ScavTrap.cpp \
	  $(CLASS)/FragTrap.cpp $(CLASS)/DiamondTrap.cpp

include ../../MakefileTemplate

#CFLAGS += -Wno-shadow#-Wshadow #-Wno-shadow
