# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/26 23:22:28 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Materia

CLASS = Class

SOURCES = main.cpp \
	  $(CLASS)/AMateria.cpp $(CLASS)/Cure.cpp $(CLASS)/Ice.cpp \
	  $(CLASS)/MateriaSource.cpp $(CLASS)/Character.cpp

include ../../MakefileTemplate
