# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/18 17:49:49 by romain           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = BSP

CLASS = Class

SOURCES = main.cpp bsp.cpp \
	  $(CLASS)/Fixed.cpp $(CLASS)/Point.cpp

include ../../MakefileTemplate
