# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/01/24 22:37:46 by romain           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Zoo

CLASS = Class

SOURCES = main.cpp \
	  $(CLASS)/Animal.cpp $(CLASS)/Dog.cpp $(CLASS)/Cat.cpp \
	  $(CLASS)/WrongAnimal.cpp $(CLASS)/WrongDog.cpp $(CLASS)/WrongCat.cpp

include ../../MakefileTemplate
