# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/02/06 16:09:41 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = MutantStack

CLASS = Class

SOURCES = main.cpp \

include ../../MakefileTemplate
