# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rsanchez <rsanchez@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/19 16:05:34 by rsanchez          #+#    #+#              #
#    Updated: 2022/02/02 19:45:36 by rsanchez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Converter

CLASS = Class

SOURCES = main.cpp \
	  $(addprefix $(CLASS)/,	\
	  Convert.cpp)

include ../../MakefileTemplate
